### ISSUE TITLE
JitPack can't build

### ISSUE THREAD

**Issue by roozbehzarei** [aptabase/aptabase-kotlin#6]
I have tested the new version `0.0.7` and Jitpack is unable to build it. That's because the new Gradle version is incompatible with Java 1.8 which your project is set to. I am making the required changes and will test them on my own fork. Will create a PR as soon as I make sure everything is compatible.
Please keep posted for a PR.

**Comment by goenning** [comment]
Done!

**Comment by goenning** [comment]
Thanks again :)

**Comment by roozbehzarei** [comment]
No problem. Your library is now successfully live. Here's the [log](https://jitpack.io/com/github/aptabase/aptabase-kotlin/0.0.8/build.log).
